name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main-agents:
    name: Nx Cloud - Main Job Agents
    runs-on: ubuntu-latest
    env:
      NX_CI_EXECUTION_ENV: agents
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Pull Request]
        with:
          fetch-depth: 0
      - run: npx nx-cloud start-ci-run --distribute-on="2 linux-medium-js"
#      - run: npx nx-cloud start-ci-run --distribute-on=".nx/workflows/dynamic.yml"

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4

      # run tasks on agents
      - run: npx nx affected -t lint test build e2e-ci

      - run: npx nx-cloud stop-all-agents
