name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main-agents:
    name: Nx Cloud - Main Job Agents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Pull Request]
        with:
          fetch-depth: 0

      - run: npx nx-cloud start-ci-run --distribute-on="2 linux-small-js"

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4

      # run js libs on agents
      - run: npx nx affected -t lint test build --exclude='*,!tag:js'

      # run react libs on main job
      - run: npx nx affected -t lint test build --exclude='*,!tag:react' --no-agents

      - run: npx nx-cloud stop-all-agents


